### ISSUE TITLE
NameError: name 'CIMultiDict' is not defined

### ISSUE THREAD

**Issue by gMan1990** [imWildCat/scylla#116]
**Describe the bug**
```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 985, in handle_request
    request, response
  File "/usr/local/lib64/python3.6/site-packages/spf/framework.py", line 653, in _run_response_middleware_18_12
    _response = await _response
  File "/usr/local/lib64/python3.6/site-packages/sanic_cors/extension.py", line 267, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/usr/local/lib64/python3.6/site-packages/sanic_cors/core.py", line 254, in set_cors_headers
    headers_to_set = get_cors_headers(options, req.headers, req.method)
  File "/usr/local/lib64/python3.6/site-packages/sanic_cors/core.py", line 175, in get_cors_headers
    headers = CIMultiDict()
NameError: name 'CIMultiDict' is not defined
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gMan1990** [comment]
see https://github.com/ashleysommer/sanic-cors/issues/34

**Comment by gMan1990** [comment]
- scylla/requirements.txt
```text
sanic==19.6.3
sanic-cors==0.9.9
```

- https://github.com/ashleysommer/sanic-cors/blob/0.9.9/sanic_cors/core.py
```python
try:
    from sanic.compat import Header
except ImportError:
    try:
        from sanic.server import CIMultiDict
    except ImportError:
        from sanic.server import CIDict as CIMultiDict
```

- https://github.com/huge-success/sanic/blob/v19.6.3/sanic/compat.py
`class Header(CIMultiDict):`

----
所以就是`from sanic.compat import Header`不会ImportError，然后就是`NameError: name 'CIMultiDict' is not defined`了。
这 code review 有木有问题？

**Comment by hittimes** [comment]
docker 启动也有这个错误 NameError: name 'CIMultiDict' is not defined

**Comment by Nolovenodie** [comment]
请问解决了吗
