### ISSUE TITLE
NameError: name 'CIMultiDict' is not defined

### ISSUE THREAD

**Issue by wencan** [imWildCat/scylla#202]
docker latest
sha256:9538b29cd157ffee0409874b590d85e4a11323c0b885e8ceda030e90004a029c

```
[2024-06-01 01:10:39 +0000] [7] [ERROR] Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 985, in handle_request
    request, response
  File "/usr/local/lib/python3.6/site-packages/spf/framework.py", line 664, in _run_response_middleware_18_12
    _response = await _response
  File "/usr/local/lib/python3.6/site-packages/sanic_cors/extension.py", line 267, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/usr/local/lib/python3.6/site-packages/sanic_cors/core.py", line 254, in set_cors_headers
    headers_to_set = get_cors_headers(options, req.headers, req.method)
  File "/usr/local/lib/python3.6/site-packages/sanic_cors/core.py", line 175, in get_cors_headers
    headers = CIMultiDict()
NameError: name 'CIMultiDict' is not defined

```

**Comment by imWildCat** [comment]
try this and ping me if still this error https://github.com/imWildCat/scylla/pkgs/container/scylla/246575661?tag=main
