### ISSUE TITLE
peewee.ImproperlyConfigured: SQLite driver not installed!

### ISSUE THREAD

**Issue by sml2h3** [imWildCat/scylla#42]
**Describe the bug**
`[root@localhost scylla]# python3 -m scylla
2018-07-15 - 14:05:41 DEBUG: create new db connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/scylla/scylla/__main__.py", line 4, in <module>
    app_main()
  File "/root/scylla/scylla/cli.py", line 84, in app_main
    sys.exit(main(sys.argv[1:]))
  File "/root/scylla/scylla/cli.py", line 50, in main
    create_db_tables()
  File "/root/scylla/scylla/database.py", line 29, in create_db_tables
    db.create_tables([ProxyIP])
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2636, in crea
te_tables
    model.create_table(**options)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 5376, in crea
te_table
    cls._schema.create_all(safe, **options)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4643, in crea
te_all
    self.create_table(safe, **table_options)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4539, in crea
te_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2533, in exec
ute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2518, in exec
ute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2504, in curs
or
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2467, in conn
ect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2699, in _con
nect
    raise ImproperlyConfigured('SQLite driver not installed!')
peewee.ImproperlyConfigured: SQLite driver not installed!`

**Comment by sml2h3** [comment]
Python3.6 Centos7

**Comment by imWildCat** [comment]
Hello, @sml2h3 , thanks for your issue.

Please note that this is not a related issue for Scylla. You should search for the solution yourself. Because sqlite has been integrated into Python since version 2.5.

I've searched for this solution for you: https://stackoverflow.com/a/51031104/2949840
Hope it works.

**Comment by zplzpl** [comment]
[root@host bin]# pip3 install pysqlite3
Collecting pysqlite3
  Using cached https://files.pythonhosted.org/packages/d5/a7/d5f6e2021cc92b1d82f89d29d830dce74d4a1ff6706eca439482bfa906c9/pysqlite3-0.3.0.tar.gz
Installing collected packages: pysqlite3
  Running setup.py install for pysqlite3 ... done
Successfully installed pysqlite3

but run scylla,it still return " peewee.ImproperlyConfigured: SQLite driver not installed!"
