### ISSUE TITLE
No OSX support?

### ISSUE THREAD

**Issue by shirshak55** [imWildCat/scylla#53]
hmm i tried with docker which says like there is no  path /var/www which is true for mac osx.

The pip3 package don't work as it shows this message

```
2019-01-08 - 02:57:58 DEBUG: create new db connection
Traceback (most recent call last):
  File "/usr/local/bin/scylla", line 11, in <module>
    sys.exit(app_main())
  File "/usr/local/lib/python3.7/site-packages/scylla/cli.py", line 84, in app_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python3.7/site-packages/scylla/cli.py", line 48, in main
    from scylla.proxy import start_forward_proxy_server_non_blocking
  File "/usr/local/lib/python3.7/site-packages/scylla/proxy/__init__.py", line 1, in <module>
    from .server import start_forward_proxy_server_non_blocking, start_forward_proxy_server
  File "/usr/local/lib/python3.7/site-packages/scylla/proxy/server.py", line 14, in <module>
    httpclient.AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient")
  File "/usr/local/lib/python3.7/site-packages/tornado/httpclient.py", line 302, in configure
    super(AsyncHTTPClient, cls).configure(impl, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tornado/util.py", line 354, in configure
    impl = import_object(impl)
  File "/usr/local/lib/python3.7/site-packages/tornado/util.py", line 181, in import_object
    obj = __import__('.'.join(parts[:-1]), None, None, [parts[-1]], 0)
  File "/usr/local/lib/python3.7/site-packages/tornado/curl_httpclient.py", line 23, in <module>
    import pycurl  # type: ignore
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)
```

And installation from source also don't work because yarn cannot work due to problem with node-sass?

Hmm any solution bro?

**Comment by ericxsun** [comment]
I met the similar error `pycurl: libcurl link-time ssl backend (none/other) is different from compile-time ssl backend (openssl)`. Solved by the following steps in my situation (hope it will help you)

- check `curl` with openssl or not
```
/usr/bin/curl --version
curl 7.43.0 (x86_64-apple-darwin14.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```

- reinstall it `curl` with openssl

```
brew uninstall curl && brew install --force curl --with-openssl
echo 'export PATH="$(brew --prefix curl)/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc
```
- install pycur

```
pip uninstall pycurl && export OPENSSL_ROOT=$(brew --prefix openssl) && export PYCURL_SSL_LIBRARY=openssl && export LDFLAGS=-L${OPENSSL_ROOT}/lib && export CFLAGS=-I${OPENSSL_ROOT}/include && export CPPFLAGS=-I${OPENSSL_ROOT}/include && pip install pycurl --compile --no-cache-dir
```

- reinstall scylla

**Comment by kushao1267** [comment]
> hmm i tried with docker which says like there is no path /var/www which is true for mac osx.
> 
> The pip3 package don't work as it shows this message
> 
> ```
> 2019-01-08 - 02:57:58 DEBUG: create new db connection
> Traceback (most recent call last):
>   File "/usr/local/bin/scylla", line 11, in <module>
>     sys.exit(app_main())
>   File "/usr/local/lib/python3.7/site-packages/scylla/cli.py", line 84, in app_main
>     sys.exit(main(sys.argv[1:]))
>   File "/usr/local/lib/python3.7/site-packages/scylla/cli.py", line 48, in main
>     from scylla.proxy import start_forward_proxy_server_non_blocking
>   File "/usr/local/lib/python3.7/site-packages/scylla/proxy/__init__.py", line 1, in <module>
>     from .server import start_forward_proxy_server_non_blocking, start_forward_proxy_server
>   File "/usr/local/lib/python3.7/site-packages/scylla/proxy/server.py", line 14, in <module>
>     httpclient.AsyncHTTPClient.configure("tornado.curl_httpclient.CurlAsyncHTTPClient")
>   File "/usr/local/lib/python3.7/site-packages/tornado/httpclient.py", line 302, in configure
>     super(AsyncHTTPClient, cls).configure(impl, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/tornado/util.py", line 354, in configure
>     impl = import_object(impl)
>   File "/usr/local/lib/python3.7/site-packages/tornado/util.py", line 181, in import_object
>     obj = __import__('.'.join(parts[:-1]), None, None, [parts[-1]], 0)
>   File "/usr/local/lib/python3.7/site-packages/tornado/curl_httpclient.py", line 23, in <module>
>     import pycurl  # type: ignore
> ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)
> ```
> And installation from source also don't work because yarn cannot work due to problem with node-sass?
> 
> Hmm any solution bro?

just run as `docker run -d -p 8899:8899 -p 8081:8081 -v ${pwd}:/var/www/scylla --name scylla wildcat/scylla:latest` can fix your problem.
