### ISSUE TITLE
Python 3.5.2 提示语法错误

### ISSUE THREAD

**Issue by CaledoniaProject** [imWildCat/scylla#60]
你好，

pip3 install scylla 装好之后，运行提示出错:

```
# /usr/local/bin/scylla
2019-01-26 - 10:45:15 DEBUG: create new db connection
Traceback (most recent call last):
  File "/usr/local/bin/scylla", line 11, in <module>
    sys.exit(app_main())
  File "/usr/local/lib/python3.5/dist-packages/scylla/cli.py", line 84, in app_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python3.5/dist-packages/scylla/cli.py", line 46, in main
    from scylla.scheduler import Scheduler
  File "/usr/local/lib/python3.5/dist-packages/scylla/scheduler.py", line 26
    provider: BaseProvider = q.get()
```

**Comment by CaledoniaProject** [comment]
看错了，原来只支持 3.6
