### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by qb1t0** [imWildCat/scylla#72]
after installed 
`sudo docker run -d -p 8899:8899 -p 8081:8081 -v /var/www/scylla:/var/www/scylla --name scylla wildcat/scylla:latest`

and 
`docker logs -f 4665a3eb98fba3e520975b32f74cea01c8b23f415f9a17bc4af0275b2946de31`
```
2019-03-28 - 09:39:08 DEBUG: create new db connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2467, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2701, in _connect
    **self.connect_params)
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2518, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2504, in cursor
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2468, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2320, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 174, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2467, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2701, in _connect
    **self.connect_params)
peewee.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/scylla/__main__.py", line 4, in <module>
    app_main()
  File "/usr/local/lib/python3.6/site-packages/scylla/cli.py", line 84, in app_main
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python3.6/site-packages/scylla/cli.py", line 50, in main
    create_db_tables()
  File "/usr/local/lib/python3.6/site-packages/scylla/database.py", line 29, in create_db_tables
    db.create_tables([ProxyIP])
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2636, in create_tables
    model.create_table(**options)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 5376, in create_table
    cls._schema.create_all(safe, **options)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4643, in create_all
    self.create_table(safe, **table_options)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4539, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2533, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2527, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2320, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 174, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2518, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2504, in cursor
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2468, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2320, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 174, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2467, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2701, in _connect
    **self.connect_params)
peewee.OperationalError: unable to open database file
```

**Comment by qb1t0** [comment]
logs after i restarted docker:
`[2019-03-28 10:15:18 +0000] [8] [INFO] Goin' Fast @ http://0.0.0.0:8899
[2019-03-28 10:15:18 +0000] [8] [INFO] Starting worker [8]
2019-03-28 - 10:15:18 INFO: Start forward proxy server on port 8081
2019-03-28 - 10:15:18 INFO:  A2uProvider: feed 13 potential proxies into the validator queue
2019-03-28 - 10:15:18 DEBUG: Get a provider from the provider queue: CoolProxyProvider
2019-03-28 - 10:15:44 DEBUG: Catch requests.Timeout for proxy ip: 103.225.223.42
2019-03-28 - 10:15:45 DEBUG: Catch requests.Timeout for proxy ip: 95.38.172.8
2019-03-28 - 10:15:48 WARNING: [Worker] Cannot get this url: https://www.cool-proxy.net/proxies/http_proxy_list/country_code:/port:/anonymous:1
2019-03-28 - 10:15:48 DEBUG: Catch requests.Timeout for proxy ip: 103.16.63.90
2019-03-28 - 10:16:18 DEBUG: Feed 12 proxies from the database for a second time validation
2019-03-28 - 10:16:18 WARNING: [Worker] Cannot get this url: https://www.cool-proxy.net/proxies/http_proxy_list/country_code:/port:/anonymous:1/page:2
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2019-03-28 - 10:16:40 DEBUG: Catch requests.RequestException for proxy ip: 112.14.47.6
2019-03-28 - 10:16:40 DEBUG: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:817: The handshake operation timed out',)))
2019-03-28 - 10:16:45 DEBUG: Catch requests.Timeout for proxy ip: 95.38.172.8
2019-03-28 - 10:16:48 WARNING: [Worker] Cannot get this url: https://www.cool-proxy.net/proxies/http_proxy_list/country_code:/port:/anonymous:1/page:3
2019-03-28 - 10:16:48 DEBUG: Get a provider from the provider queue: Data5uProvider
2019-03-28 - 10:16:50 INFO:  Data5uProvider: feed 15 potential proxies into the validator queue
2019-03-28 - 10:16:50 DEBUG: Catch requests.RequestException for proxy ip: 151.80.36.115
2019-03-28 - 10:16:50 DEBUG: HTTPConnectionPool(host='151.80.36.115', port=8189): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909f74a748>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2019-03-28 - 10:16:50 DEBUG: Catch requests.RequestException for proxy ip: 77.85.223.12
2019-03-28 - 10:16:50 DEBUG: HTTPConnectionPool(host='77.85.223.12', port=9010): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90981577f0>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2019-03-28 - 10:16:50 DEBUG: Catch requests.RequestException for proxy ip: 130.237.3.229
2019-03-28 - 10:16:50 DEBUG: HTTPConnectionPool(host='130.237.3.229', port=8609): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90981a6518>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2019-03-28 - 10:16:50 DEBUG: Catch requests.RequestException for proxy ip: 91.210.178.161
2019-03-28 - 10:16:50 DEBUG: HTTPConnectionPool(host='91.210.178.161', port=8596): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9098160e48>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2019-03-28 - 10:16:50 DEBUG: Catch requests.RequestException for proxy ip: 185.34.17.248
2019-03-28 - 10:16:50 DEBUG: HTTPConnectionPool(host='185.34.17.248', port=8092): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9098160e10>: Failed to establish a new connection: [Errno 111] Connection refused',)))
`
and lower 

`2019-03-28 - 10:17:40 DEBUG: Catch requests.Timeout for proxy ip: 109.70.201.2
2019-03-28 - 10:17:43 DEBUG: Catch requests.RequestException for proxy ip: 192.238.189.26
2019-03-28 - 10:17:43 DEBUG: HTTPConnectionPool(host='192.238.189.26', port=8081): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2019-03-28 - 10:17:43 DEBUG: Catch requests.Timeout for proxy ip: 109.110.55.230
2019-03-28 - 10:17:45 DEBUG: Catch requests.RequestException for proxy ip: 118.179.156.246
2019-03-28 - 10:17:45 DEBUG: HTTPConnectionPool(host='118.179.156.246', port=51989): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2019-03-28 - 10:17:47 DEBUG: Catch requests.Timeout for proxy ip: 95.170.220.9
2019-03-28 - 10:17:49 DEBUG: Catch requests.RequestException for proxy ip: 87.76.10.119
2019-03-28 - 10:17:49 DEBUG: HTTPConnectionPool(host='87.76.10.119', port=53281): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2019-03-28 - 10:17:50 DEBUG: Catch requests.Timeout for proxy ip: 118.174.232.47
2019-03-28 - 10:17:52 DEBUG: Catch requests.Timeout for proxy ip: 92.62.236.73
2019-03-28 - 10:17:54 DEBUG: Catch requests.Timeout for proxy ip: 78.186.38.189
2019-03-28 - 10:17:54 DEBUG: Catch requests.Timeout for proxy ip: 94.253.15.130
2019-03-28 - 10:17:55 DEBUG: Catch requests.Timeout for proxy ip: 198.211.109.21
2019-03-28 - 10:17:57 DEBUG: Catch requests.Timeout for proxy ip: 103.80.238.205
2019-03-28 - 10:17:59 DEBUG: Catch requests.Timeout for proxy ip: 197.243.228.149
2019-03-28 - 10:17:59 DEBUG: Catch requests.RequestException for proxy ip: 42.116.18.172
2019-03-28 - 10:17:59 DEBUG: HTTPConnectionPool(host='42.116.18.172', port=40026): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2019-03-28 - 10:18:01 DEBUG: Catch requests.Timeout for proxy ip: 184.75.249.195
2019-03-28 - 10:18:01 DEBUG: Catch requests.RequestException for proxy ip: 134.119.205.165
2019-03-28 - 10:18:01 DEBUG: HTTPConnectionPool(host='134.119.205.165', port=1080): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2019-03-28 - 10:18:02 DEBUG: Catch requests.RequestException for proxy ip: 192.238.189.6
2019-03-28 - 10:18:02 DEBUG: HTTPConnectionPool(host='192.238.189.6', port=8081): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9090607b38>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2019-03-28 - 10:18:03 DEBUG: Catch requests.Timeout for proxy ip: 170.0.112.2
2019-03-28 - 10:18:04 DEBUG: Catch requests.Timeout for proxy ip: 188.43.4.117
2019-03-28 - 10:18:05 DEBUG: Catch requests.Timeout for proxy ip: 117.196.238.124
2019-03-28 - 10:18:07 DEBUG: Catch requests.RequestException for proxy ip: 130.185.95.195
2019-03-28 - 10:18:07 DEBUG: Exceeded 30 redirects.
2019-03-28 - 10:18:08 DEBUG: Catch requests.Timeout for proxy ip: 37.32.37.70
2019-03-28 - 10:18:10 DEBUG: Catch requests.Timeout for proxy ip: 85.9.96.118
2019-03-28 - 10:18:11 DEBUG: Catch requests.Timeout for proxy ip: 118.174.232.185
2019-03-28 - 10:18:11 DEBUG: Catch requests.RequestException for proxy ip: 68.183.105.251
2019-03-28 - 10:18:11 DEBUG: HTTPConnectionPool(host='68.183.105.251', port=80): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2019-03-28 - 10:18:12 DEBUG: Catch requests.Timeout for proxy ip: 109.122.242.106
2019-03-28 - 10:18:12 DEBUG: Catch requests.Timeout for proxy ip: 178.252.133.62
2019-03-28 - 10:18:17 DEBUG: Catch requests.Timeout for proxy ip: 178.252.166.187
2019-03-28 - 10:18:17 DEBUG: Catch requests.Timeout for proxy ip: 114.129.23.25
2019-03-28 - 10:18:17 DEBUG: Catch requests.Timeout for proxy ip: 178.252.168.193
2019-03-28 - 10:18:17 DEBUG: Catch requests.Timeout for proxy ip: 103.192.168.105
2019-03-28 - 10:18:17 DEBUG: Catch requests.Timeout for proxy ip: 85.9.88.165
2019-03-28 - 10:18:19 DEBUG: Catch requests.Timeout for proxy ip: 131.196.143.68
2019-03-28 - 10:18:19 DEBUG: Catch requests.Timeout for proxy ip: 118.243.175.26
2019-03-28 - 10:18:20 DEBUG: Catch requests.Timeout for proxy ip: 178.252.142.181
2019-03-28 - 10:18:20 DEBUG: Catch requests.Timeout for proxy ip: 178.252.166.189
2019-03-28 - 10:18:20 DEBUG: Catch requests.RequestException for proxy ip: 192.238.189.81
2019-03-28 - 10:18:20 DEBUG: HTTPConnectionPool(host='192.238.189.81', port=8081): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909058a208>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2019-03-28 - 10:18:21 DEBUG: Catch requests.Timeout for proxy ip: 129.0.152.115
2019-03-28 - 10:18:22 DEBUG: Catch requests.Timeout for proxy ip: 178.252.166.190
2019-03-28 - 10:18:22 DEBUG: Catch requests.Timeout for proxy ip: 178.252.167.51
2019-03-28 - 10:18:23 DEBUG: Catch requests.RequestException for proxy ip: 177.46.149.22
2019-03-28 - 10:18:23 DEBUG: HTTPConnectionPool(host='177.46.149.22', port=41273): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2019-03-28 - 10:18:25 DEBUG: Catch requests.Timeout for proxy ip: 109.122.240.214
`

**Comment by qb1t0** [comment]
**logs after i restarted docker:**
```
[2019-03-28 10:15:18 +0000] [8] [INFO] Goin' Fast @ http://0.0.0.0:8899
[2019-03-28 10:15:18 +0000] [8] [INFO] Starting worker [8]
2019-03-28 - 10:15:18 INFO: Start forward proxy server on port 8081
2019-03-28 - 10:15:18 INFO:  A2uProvider: feed 13 potential proxies into the validator queue
2019-03-28 - 10:15:18 DEBUG: Get a provider from the provider queue: CoolProxyProvider
2019-03-28 - 10:15:44 DEBUG: Catch requests.Timeout for proxy ip: 103.225.223.42
2019-03-28 - 10:15:45 DEBUG: Catch requests.Timeout for proxy ip: 95.38.172.8
2019-03-28 - 10:15:48 WARNING: [Worker] Cannot get this url: https://www.cool-proxy.net/proxies/http_proxy_list/country_code:/port:/anonymous:1
2019-03-28 - 10:15:48 DEBUG: Catch requests.Timeout for proxy ip: 103.16.63.90
2019-03-28 - 10:16:18 DEBUG: Feed 12 proxies from the database for a second time validation
2019-03-28 - 10:16:18 WARNING: [Worker] Cannot get this url: https://www.cool-proxy.net/proxies/http_proxy_list/country_code:/port:/anonymous:1/page:2
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2019-03-28 - 10:16:40 DEBUG: Catch requests.RequestException for proxy ip: 112.14.47.6
2019-03-28 - 10:16:40 DEBUG: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: /?format=json (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:817: The handshake operation timed out',)))
2019-03-28 - 10:16:45 DEBUG: Catch requests.Timeout for proxy ip: 95.38.172.8
2019-03-28 - 10:16:48 WARNING: [Worker] Cannot get this url: https://www.cool-proxy.net/proxies/http_proxy_list/country_code:/port:/anonymous:1/page:3
2019-03-28 - 10:16:48 DEBUG: Get a provider from the provider queue: Data5uProvider
2019-03-28 - 10:16:50 INFO:  Data5uProvider: feed 15 potential proxies into the validator queue
2019-03-28 - 10:16:50 DEBUG: Catch requests.RequestException for proxy ip: 151.80.36.115
2019-03-28 - 10:16:50 DEBUG: HTTPConnectionPool(host='151.80.36.115', port=8189): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f909f74a748>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2019-03-28 - 10:16:50 DEBUG: Catch requests.RequestException for proxy ip: 77.85.223.12
2019-03-28 - 10:16:50 DEBUG: HTTPConnectionPool(host='77.85.223.12', port=9010): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90981577f0>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2019-03-28 - 10:16:50 DEBUG: Catch requests.RequestException for proxy ip: 130.237.3.229
```
**a bit lower**

```
2019-03-28 - 10:20:21 DEBUG: Catch requests.RequestException for proxy ip: 94.130.126.87
2019-03-28 - 10:20:21 DEBUG: HTTPConnectionPool(host='94.130.126.87', port=80): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2019-03-28 - 10:20:23 DEBUG: Catch requests.Timeout for proxy ip: 191.241.34.210
2019-03-28 - 10:20:23 DEBUG: Catch requests.Timeout for proxy ip: 185.33.34.76
2019-03-28 - 10:20:23 DEBUG: Catch requests.RequestException for proxy ip: 209.97.161.88
2019-03-28 - 10:20:23 DEBUG: HTTPConnectionPool(host='209.97.161.88', port=8080): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90905a7f28>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2019-03-28 - 10:20:24 DEBUG: Catch requests.Timeout for proxy ip: 41.169.9.170
2019-03-28 - 10:20:25 DEBUG: Catch requests.RequestException for proxy ip: 36.65.161.41
2019-03-28 - 10:20:25 DEBUG: HTTPConnectionPool(host='36.65.161.41', port=8080): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90905a7f98>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2019-03-28 - 10:20:25 DEBUG: Catch requests.Timeout for proxy ip: 190.60.103.178
2019-03-28 - 10:20:25 DEBUG: Catch requests.Timeout for proxy ip: 46.99.255.235
2019-03-28 - 10:20:26 DEBUG: Catch requests.Timeout for proxy ip: 138.97.152.42
2019-03-28 - 10:20:29 DEBUG: Catch requests.Timeout for proxy ip: 103.87.104.137
2019-03-28 - 10:20:31 DEBUG: Catch requests.Timeout for proxy ip: 202.29.223.154
2019-03-28 - 10:20:35 DEBUG: Catch requests.Timeout for proxy ip: 118.173.232.170
2019-03-28 - 10:20:37 DEBUG: Catch requests.Timeout for proxy ip: 103.206.112.49
2019-03-28 - 10:20:37 DEBUG: Catch requests.Timeout for proxy ip: 41.216.98.22
2019-03-28 - 10:20:41 DEBUG: Catch requests.Timeout for proxy ip: 27.147.215.188
2019-03-28 - 10:20:41 DEBUG: Catch requests.RequestException for proxy ip: 103.94.125.110
2019-03-28 - 10:20:41 DEBUG: HTTPConnectionPool(host='103.94.125.110', port=8080): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9090754828>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2019-03-28 - 10:20:42 DEBUG: Catch requests.Timeout for proxy ip: 180.241.162.67
2019-03-28 - 10:20:42 DEBUG: Catch requests.Timeout for proxy ip: 118.174.45.114
2019-03-28 - 10:20:44 DEBUG: Catch requests.Timeout for proxy ip: 103.17.38.24
2019-03-28 - 10:20:45 DEBUG: Catch requests.Timeout for proxy ip: 201.217.28.240
2019-03-28 - 10:20:48 DEBUG: Catch requests.Timeout for proxy ip: 119.192.179.46
2019-03-28 - 10:20:49 DEBUG: Catch requests.Timeout for proxy ip: 190.102.156.170
2019-03-28 - 10:20:49 DEBUG: Catch requests.Timeout for proxy ip: 89.229.186.216
2019-03-28 - 10:20:54 DEBUG: Catch requests.Timeout for proxy ip: 190.151.86.210
2019-03-28 - 10:20:57 DEBUG: Catch requests.Timeout for proxy ip: 146.88.37.15
2019-03-28 - 10:20:58 DEBUG: Catch requests.Timeout for proxy ip: 182.253.249.59
2019-03-28 - 10:20:59 DEBUG: Catch requests.RequestException for proxy ip: 203.202.240.53
2019-03-28 - 10:20:59 DEBUG: HTTPConnectionPool(host='203.202.240.53', port=8080): Max retries exceeded with url: http://api.ipify.org/?format=json (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2019-03-28 - 10:21:01 DEBUG: Catch requests.Timeout for proxy ip: 36.66.124.157
2019-03-28 - 10:21:01 DEBUG: Catch requests.Timeout for proxy ip: 159.192.107.105
2019-03-28 - 10:21:02 DEBUG: Catch requests.Timeout for proxy ip: 117.2.155.139
2019-03-28 - 10:21:03 DEBUG: Catch requests.Timeout for proxy ip: 117.254.218.23
2019-03-28 - 10:21:04 DEBUG: Catch requests.Timeout for proxy ip: 169.239.167.4
2019-03-28 - 10:21:06 DEBUG: Catch requests.Timeout for proxy ip: 41.211.116.134
2019-03-28 - 10:21:07 DEBUG: Catch requests.Timeout for proxy ip: 36.71.213.22
```
