### ISSUE TITLE
fetch_ips 没有捕获ConnectionError，导致不能持续获取新的proxy.

### ISSUE THREAD

**Issue by saukymo** [imWildCat/scylla#74]
在执行下面这步获取provider ip的时候有时候会出错：
``` python
html = worker.get_html(url, render_js=provider.should_render_js())
```
错误日志：
```
2019-03-26 - 04:23:08 DEBUG: starting render js...
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/scylla/scheduler.py", line 34, in fetch_ips
    html = worker.get_html(url, render_js=provider.should_render_js())
  File "/usr/local/lib/python3.6/site-packages/scylla/worker.py", line 47, in get_html
    response.html.render(wait=1.5, timeout=10.0)
  File "/usr/local/lib/python3.6/site-packages/requests_html.py", line 583, in render
    content, result, page = self.session.loop.run_until_complete(_async_render(url=self.url, script=script, sleep=sleep, wait=wait, content=self.html, reload=reload, scrolldown=scrolldown, timeout=timeout, keep_page=keep_page))
  File "uvloop/loop.pyx", line 1446, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.6/site-packages/requests_html.py", line 538, in _async_render
    page = await self.session.browser.newPage()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/browser.py", line 192, in newPage
    return await self._defaultContext.newPage()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/browser.py", line 329, in newPage
    return await self._browser._createPageInContext(self._id)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/browser.py", line 200, in _createPageInContext
    'Target.createTarget', options)).get('targetId')
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/connection.py", line 85, in send
    raise ConnectionError('Connection is closed')
ConnectionError: Connection is closed
```

这之后就没有再执行过fetch ips操作，现象就是运行一段时间后，proxy总量一直不变，可用的ip越来越少。

**Comment by imWildCat** [comment]
Closed due to unstructured content.
